Import de Pandas y cargar el dataset:

In [ ]:
import pandas as pd

df= pd.read_csv('../data/1900_2021_DISASTERS.xlsx - emdat data.csv')

#Ver primeras líneas, cuántas filas y columnas hay, ver los valores nulos, los tipo de datos y las estadísticas básicas.

In [ ]:
df.head()

df.shape

df.columns.tolist()

df.info()

df. describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16126 entries, 0 to 16125
Data columns (total 45 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Year                        16126 non-null  int64
 1   Seq                         16126 non-null  int64
 2   Glide                       1581 non-null   object
 3   Disaster Group              16126 non-null  object
 4   Disaster Subgroup           16126 non-null  object
 5   Disaster Type               16126 non-null  object
 6   Disaster Subtype            13016 non-null  object
 7   Disaster Subsubtype         1077 non-null   object
 8   Event Name                  3861 non-null   object
 9   Country                     16126 non-null  object
 10  ISO                         16126 non-null  object
 11  Region                      16126 non-null  object
 12  Continent                   16126 non-null  object
 13  Location                    14334 non-null  object
 14  Origin                      3794 non-null   object
 15  Associated Dis              3348 non-null   object
 16  Associated Dis2             707 non-null    object
 17  OFDA Response               1694 non-null   object
 18  Appeal                      2569 non-null   object
 19  Declaration                 3256 non-null   object
 20  Aid Contribution            677 non-null    float64
 21  Dis Mag Value               4946 non-null   float64
 22  Dis Mag Scale               14936 non-null  object
 23  Latitude                    2729 non-null   object
 24  Longitude                   2732 non-null   object
 25  Local Time                  1103 non-null   object
 26  River Basin                 1287 non-null   object
 27  Start Year                  16126 non-null  int64
 28  Start Month                 15739 non-null  float64
 29  Start Day                   12498 non-null  float64
 30  End Year                    16126 non-null  int64
 31  End Month                   15418 non-null  float64
 32  End Day                     12570 non-null  float64
 33  Total Deaths                11413 non-null  float64
 34  No Injured                  3895 non-null   float64
 35  No Affected                 9220 non-null   float64
 36  No Homeless                 2430 non-null   float64
 37  Total Affected              11617 non-null  float64
 38  Insured Damages ('000 US$)  1096 non-null   float64
 39  Total Damages ('000 US$)    5245 non-null   float64
 40  CPI                         15811 non-null  float64
 41  Adm Level                   7859 non-null   object
 42  Admin1 Code                 4581 non-null   object
 43  Admin2 Code                 3969 non-null   object
 44  Geo Locations               7859 non-null   object
dtypes: float64(14), int64(4), object(27)
memory usage: 5.5+ MB

,Year,Seq,Aid Contribution,Dis Mag Value,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No Injured,No Affected,No Homeless,Total Affected,Insured Damages ('000 US$),Total Damages ('000 US$),CPI
count,16126.000000,16126.000000,6.770000e+02,4.946000e+03,16126.00000,15739.000000,12498.000000,16126.000000,15418.000000,12570.000000,1.141300e+04,3.895000e+03,9.220000e+03,2.430000e+03,1.161700e+04,1.096000e+03,5.245000e+03,15811.000000
mean,1996.764790,714.784820,1.254136e+05,4.735038e+04,1996.77837,6.444374,15.233957,1996.835607,6.576728,15.775020,2.842866e+03,2.621102e+03,8.823612e+05,7.329314e+04,7.165088e+05,7.986514e+05,7.247835e+05,63.215103
std,20.159065,1929.635089,2.997875e+06,3.094242e+05,20.15571,3.393965,8.953821,20.143010,3.352965,8.865486,6.860595e+04,3.440343e+04,8.573913e+06,5.230058e+05,7.718598e+06,3.057638e+06,4.723131e+06,26.734285
min,1900.000000,1.000000,1.000000e+00,-5.700000e+01,1900.00000,1.000000,1.000000,1900.000000,1.000000,1.000000,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,1.000000e+00,3.400000e+01,2.000000e+00,3.221647
25%,1989.000000,93.000000,1.750000e+02,7.000000e+00,1989.00000,4.000000,7.000000,1989.000000,4.000000,8.000000,6.000000e+00,1.400000e+01,1.244750e+03,5.725000e+02,6.500000e+02,5.000000e+04,8.300000e+03,45.692897
50%,2001.000000,270.000000,7.210000e+02,1.515000e+02,2001.00000,7.000000,15.000000,2001.000000,7.000000,16.000000,2.000000e+01,5.000000e+01,1.000000e+04,3.000000e+03,5.965000e+03,1.725000e+05,6.000000e+04,68.415379
75%,2011.000000,486.000000,3.511000e+03,1.129650e+04,2011.00000,9.000000,23.000000,2011.000000,9.000000,23.000000,6.300000e+01,2.000000e+02,9.182300e+04,1.750000e+04,5.825500e+04,5.000000e+05,3.173000e+05,84.252733
max,2021.000000,9881.000000,7.800000e+07,1.302587e+07,2021.00000,12.000000,31.000000,2021.000000,12.000000,31.000000,3.700000e+06,1.800000e+06,3.300000e+08,1.585000e+07,3.300000e+08,6.000000e+07,2.100000e+08,100.000000

Elimino las columnas que ya no me hacen falta

In [ ]:
cols_to_drop= ['Seq', 'Glide', 'Disaster Subsubtype', 'Event Name','Origin','Associated Dis', 'Associated Dis2','OFDA Response', 'Appeal', 'Declaration',
    'Aid Contribution', 'Dis Mag Value', 'Dis Mag Scale',
    'Latitude', 'Longitude', 'Local Time', 'River Basin',
    'Start Month', 'Start Day', 'End Month', 'End Day',
    'No Injured', 'No Homeless', 'Insured Damages (\'000 US$)',
    'Adm Level', 'Admin1 Code', 'Admin2 Code', 'Geo Locations']

df_clean= df.drop(columns=cols_to_drop)
df_clean.shape

(16126, 17)

Revisasmos los datos nulos que hay

In [8]:
df_clean.isnull().sum()

Year                            0
Disaster Group                  0
Disaster Subgroup               0
Disaster Type                   0
Disaster Subtype             3110
Country                         0
ISO                             0
Region                          0
Continent                       0
Location                     1792
Start Year                      0
End Year                        0
Total Deaths                 4713
No Affected                  6906
Total Affected               4509
Total Damages ('000 US$)    10881
CPI                           315
dtype: int64

Para saber que hacer con los nulos, calculo el porcentaje de nulos para saber si tengo que eliminarlos o rellenarlos con la media/mediana

In [9]:
round(df_clean.isnull().sum() / len(df_clean) * 100, 2)

Year                         0.00
Disaster Group               0.00
Disaster Subgroup            0.00
Disaster Type                0.00
Disaster Subtype            19.29
Country                      0.00
ISO                          0.00
Region                       0.00
Continent                    0.00
Location                    11.11
Start Year                   0.00
End Year                     0.00
Total Deaths                29.23
No Affected                 42.83
Total Affected              27.96
Total Damages ('000 US$)    67.47
CPI                          1.95
dtype: float64

CPI tiene porcentaje de nulos de 2% asi que rellenare con la mediana.
Disaster Subtype y Location sigue siendo un porcentaje bajo 19 y 11%, así que creo que será buena idea rellenar con Desconocido/Unknown.
Total Deaths, No Affected, Total Affected, son porcentajes un poco más altos pero creo que será buena idea rellenar con 0 porque creo que no es que haya errores, sino que a lo mejor no se rellenaron los datos y creo que son importantes.
Total Damages eliminaré la columna porque tiene muchos nulos.

Primero voy a cambiar todo a minúsculas y reemplazar los espacios por _, y también quitar símbolos especiales para evitar posibles errores en la escritura del código

In [10]:
df_clean.columns= (df_clean.columns
                   .str.lower()
                   .str.replace(' ', '_')
                   .str.replace("'", '')
                   .str.replace('(','')
                   .str.replace(')', '')
                   .str.replace('$', ''))

df_clean.columns.tolist()

['year',
 'disaster_group',
 'disaster_subgroup',
 'disaster_type',
 'disaster_subtype',
 'country',
 'iso',
 'region',
 'continent',
 'location',
 'start_year',
 'end_year',
 'total_deaths',
 'no_affected',
 'total_affected',
 'total_damages_000_us',
 'cpi']

Elimino Total Damages como he dicho antes

In [11]:
df_clean= df_clean.drop(columns=['total_damages_000_us'])

Relleno los nulos en Disaster Subtype y Location con la palabra Unknown

In [12]:
df_clean['disaster_subtype']= df_clean['disaster_subtype'].fillna('Unknown')
df_clean['location']= df_clean['location'].fillna('Unknown')

Relleno los nulos en Total Deaths, No Affected y Total Affected con un 0

In [13]:
df_clean['total_deaths']= df_clean['total_deaths'].fillna(0)
df_clean['no_affected']= df_clean['no_affected'].fillna(0)
df_clean['total_affected']= df_clean['total_affected'].fillna(0)

Relleno con la mediana en CPI

In [14]:
df_clean['cpi']= df_clean['cpi'].fillna(df_clean['cpi'].median())

Comprobamos que ahora en ninguno no hay nulos

In [15]:
df_clean.isnull().sum()

year                 0
disaster_group       0
disaster_subgroup    0
disaster_type        0
disaster_subtype     0
country              0
iso                  0
region               0
continent            0
location             0
start_year           0
end_year             0
total_deaths         0
no_affected          0
total_affected       0
cpi                  0
dtype: int64

Ahora tengo que ver si hay datos duplicados

In [16]:
df_clean.duplicated().sum()

np.int64(55)

Hay datos duplicados, pero también necesito que tipo de datos son

In [17]:
df_clean.dtypes

year                   int64
disaster_group        object
disaster_subgroup     object
disaster_type         object
disaster_subtype      object
country               object
iso                   object
region                object
continent             object
location              object
start_year             int64
end_year               int64
total_deaths         float64
no_affected          float64
total_affected       float64
cpi                  float64
dtype: object

Veo que hay float así que los voy a pasar a integer porque no tiene sentido que en Total Deaths, No Affected y Total Affected haya decimales.

Ahora voy a quitar los 55 duplicados que no necesito

In [18]:
df_clean[df_clean.duplicated()]

,year,disaster_group,disaster_subgroup,disaster_type,disaster_subtype,country,iso,region,continent,location,start_year,end_year,total_deaths,no_affected,total_affected,cpi
508,1969,Natural,Climatological,Wildfire,"Land fire (Brush, Bush, Pasture)",Hong Kong,HKG,Eastern Asia,Asia,Unknown,1969,1969,0.0,0.0,0.0,14.173782
550,1970,Natural,Climatological,Wildfire,"Land fire (Brush, Bush, Pasture)",Hong Kong,HKG,Eastern Asia,Asia,Unknown,1970,1970,0.0,0.0,0.0,15.001282
579,1971,Natural,Climatological,Wildfire,"Land fire (Brush, Bush, Pasture)",Hong Kong,HKG,Eastern Asia,Asia,Unknown,1971,1971,0.0,0.0,0.0,15.645257
596,1972,Natural,Climatological,Wildfire,"Land fire (Brush, Bush, Pasture)",Hong Kong,HKG,Eastern Asia,Asia,Unknown,1972,1972,0.0,0.0,0.0,16.157212
597,1972,Natural,Climatological,Wildfire,"Land fire (Brush, Bush, Pasture)",Hong Kong,HKG,Eastern Asia,Asia,Unknown,1972,1972,0.0,0.0,0.0,16.157212
631,1973,Natural,Climatological,Wildfire,"Land fire (Brush, Bush, Pasture)",Hong Kong,HKG,Eastern Asia,Asia,Unknown,1973,1973,0.0,0.0,0.0,17.155360
664,1974,Natural,Climatological,Wildfire,"Land fire (Brush, Bush, Pasture)",Hong Kong,HKG,Eastern Asia,Asia,Unknown,1974,1974,0.0,0.0,0.0,19.051854
665,1974,Natural,Climatological,Wildfire,"Land fire (Brush, Bush, Pasture)",Hong Kong,HKG,Eastern Asia,Asia,Unknown,1974,1974,0.0,0.0,0.0,19.051854
706,1976,Natural,Meteorological,Storm,Tropical cyclone,Australia,AUS,Australia and New Zealand,Oceania,Queensland,1976,1976,0.0,0.0,0.0,21.988357
1039,1945,Natural,Geophysical,Earthquake,Ground movement,Romania,ROU,Eastern Europe,Europe,Unknown,1945,1945,0.0,0.0,0.0,6.971645
2034,1978,Natural,Climatological,Wildfire,"Land fire (Brush, Bush, Pasture)",Hong Kong,HKG,Eastern Asia,Asia,Unknown,1978,1978,0.0,0.0,0.0,25.204991
2073,1979,Natural,Climatological,Wildfire,"Land fire (Brush, Bush, Pasture)",Hong Kong,HKG,Eastern Asia,Asia,Unknown,1979,1979,0.0,0.0,0.0,28.041681
2084,1980,Natural,Meteorological,Storm,Tropical cyclone,Australia,AUS,Australia and New Zealand,Oceania,Pilbara,1980,1980,0.0,0.0,0.0,31.841107
2124,1980,Natural,Climatological,Wildfire,"Land fire (Brush, Bush, Pasture)",Hong Kong,HKG,Eastern Asia,Asia,Unknown,1980,1980,0.0,0.0,0.0,31.841107
3441,1978,Natural,Meteorological,Storm,Unknown,United States of America (the),USA,Northern America,Americas,Unknown,1978,1978,25.0,0.0,0.0,25.204991
3761,1988,Natural,Meteorological,Storm,Unknown,United States of America (the),USA,Northern America,Americas,California,1988,1988,0.0,0.0,0.0,45.692897
3856,1990,Natural,Meteorological,Storm,Convective storm,Austria,AUT,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
3858,1990,Natural,Meteorological,Storm,Unknown,Austria,AUT,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
3862,1990,Natural,Meteorological,Storm,Unknown,Belgium,BEL,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
3863,1990,Natural,Meteorological,Storm,Unknown,Belgium,BEL,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
3886,1990,Natural,Meteorological,Storm,Unknown,Switzerland,CHE,Western Europe,Europe,Unknown,1990,1990,1.0,0.0,0.0,50.484032
3924,1990,Natural,Meteorological,Storm,Unknown,Denmark,DNK,Northern Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4279,1990,Natural,Meteorological,Storm,Unknown,Finland,FIN,Northern Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4288,1990,Natural,Meteorological,Storm,Unknown,France,FRA,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4289,1990,Natural,Meteorological,Storm,Unknown,France,FRA,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4290,1990,Natural,Meteorological,Storm,Unknown,France,FRA,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4292,1990,Natural,Meteorological,Storm,Unknown,France,FRA,Western Europe,Europe,Unknown,1990,1990,10.0,0.0,0.0,50.484032
4296,1990,Natural,Meteorological,Storm,Unknown,United Kingdom of Great Britain and Northern I...,GBR,Northern Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4297,1990,Natural,Meteorological,Storm,Unknown,United Kingdom of Great Britain and Northern I...,GBR,Northern Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4298,1990,Natural,Meteorological,Storm,Unknown,United Kingdom of Great Britain and Northern I...,GBR,Northern Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4300,1990,Natural,Meteorological,Storm,Unknown,United Kingdom of Great Britain and Northern I...,GBR,Northern Europe,Europe,Unknown,1990,1990,18.0,0.0,0.0,50.484032
4328,1990,Natural,Meteorological,Storm,Unknown,Ireland,IRL,Northern Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4330,1990,Natural,Meteorological,Storm,Unknown,Ireland,IRL,Northern Europe,Europe,Unknown,1990,1990,1.0,0.0,0.0,50.484032
4355,1990,Natural,Meteorological,Storm,Unknown,Luxembourg,LUX,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4356,1990,Natural,Meteorological,Storm,Unknown,Luxembourg,LUX,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4357,1990,Natural,Meteorological,Storm,Unknown,Luxembourg,LUX,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4358,1990,Natural,Meteorological,Storm,Unknown,Luxembourg,LUX,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4359,1990,Natural,Meteorological,Storm,Unknown,Luxembourg,LUX,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4374,1990,Natural,Meteorological,Storm,Unknown,Netherlands (the),NLD,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4375,1990,Natural,Meteorological,Storm,Unknown,Netherlands (the),NLD,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4376,1990,Natural,Meteorological,Storm,Unknown,Netherlands (the),NLD,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4377,1990,Natural,Meteorological,Storm,Unknown,Netherlands (the),NLD,Western Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4379,1990,Natural,Meteorological,Storm,Unknown,Norway,NOR,Northern Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
4801,1989,Natural,Meteorological,Storm,Unknown,United States of America (the),USA,Northern America,Americas,Unknown,1989,1989,0.0,0.0,0.0,47.898497
4803,1989,Natural,Meteorological,Storm,Unknown,United States of America (the),USA,Northern America,Americas,Unknown,1989,1989,0.0,0.0,0.0,47.898497
4809,1989,Natural,Meteorological,Storm,Unknown,United States of America (the),USA,Northern America,Americas,Unknown,1989,1989,0.0,0.0,0.0,47.898497
4842,1990,Natural,Meteorological,Storm,Unknown,Sweden,SWE,Northern Europe,Europe,Unknown,1990,1990,0.0,0.0,0.0,50.484032
5136,1994,Natural,Meteorological,Storm,Convective storm,Brazil,BRA,South America,Americas,Sao Paulo,1994,1994,0.0,0.0,1000.0,57.271483
8045,2002,Natural,Meteorological,Storm,Unknown,Japan,JPN,Eastern Asia,Asia,Okinawa province,2002,2002,1.0,0.0,0.0,69.500473
10404,2007,Natural,Hydrological,Flood,Riverine flood,China,CHN,Eastern Asia,Asia,Ankang district (Shaanxi Sheng province),2007,2007,11.0,0.0,17500.0,80.113393
12361,2013,Natural,Meteorological,Storm,Extra-tropical storm,Belgium,BEL,Western Europe,Europe,"Region de Bruxelles-Capitale, Vlaams Gewest, R...",2013,2013,0.0,0.0,0.0,90.010440
12419,2013,Natural,Meteorological,Storm,Extra-tropical storm,Denmark,DNK,Northern Europe,Europe,"Aarhus, Bornholm, Frederiksberg, Fyn, Nordjyll...",2013,2013,1.0,0.0,0.0,90.010440
13031,2014,Natural,Hydrological,Flood,Riverine flood,Côte d’Ivoire,CIV,Western Africa,Africa,Abidjan district (District autonome de Abidjan...,2014,2014,23.0,0.0,0.0,91.470614
13805,2014,Natural,Meteorological,Storm,Tropical cyclone,Taiwan (Province of China),TWN,Eastern Asia,Asia,Taiwan Sheng province,2014,2014,0.0,0.0,0.0,91.470614
15971,1925,Natural,Geophysical,Earthquake,Ground movement,United States of America (the),USA,Northern America,Americas,Santa Barbara (California),1925,1925,13.0,0.0,0.0,6.791232

Veo que hay Duplicados completos: Que son los que coinciden en absolutamente todo.Y filas similares, que coinciden varios datos pero no todos. Así que los completos los voy a eliminar enteros

In [19]:
df_clean= df_clean.drop_duplicates()
print(f"Filas antes: 16126")
print(f"Filas después: {len(df_clean)}")
print(f"Duplicados eliminados: {16126 - len(df_clean)}")

Filas antes: 16126
Filas después: 16071
Duplicados eliminados: 55

Ahora que están eliminados los duplicados y comprobado, voy a corregir floats a int

In [20]:
df_clean['total_deaths']= df_clean['total_deaths'].astype(int)
df_clean['no_affected']= df_clean['no_affected'].astype(int)
df_clean['total_affected']= df_clean['total_affected'].astype(int)
df_clean.dtypes

year                   int64
disaster_group        object
disaster_subgroup     object
disaster_type         object
disaster_subtype      object
country               object
iso                   object
region                object
continent             object
location              object
start_year             int64
end_year               int64
total_deaths           int64
no_affected            int64
total_affected         int64
cpi                  float64
dtype: object

Para que no se me pierda nada, voy a guardar con todo esto el DataSet ya limpio

In [21]:
df_clean.to_csv('../data/disasters_clean.csv', index=False)
print('Dataset guardado correctamente')

Dataset guardado correctamente

In [23]:
import sys
sys.path.append("..")

from src.cleaning import clean_disasters

df_clean = clean_disasters("../data/1900_2021_DISASTERS.xlsx - emdat data.csv")

Dataset limpio: 16071 filas, 16 columnas ✅